### PR TITLE
Extract Profile out to its own type. -- Do not pull yet.

### PR DESCRIPTION
**Pull request by chibill**
So far I have added all the encryption and auth types to the Constants and also setup what basic varibles a Profile has. Working on the xml parser to set the data.

### CODE REVIEW

**Comment by awkman** [comment]
Thanks for your PR. Now, I am working on enabling this PR to support in both Windows and Linux.
I will separate 'auth_alg: open, shared', 'auth key mgmt: wpa, wpa2, wpapsk, wpa2psk', 'cipher: none, wep, tkip, ccmp(aes)'

**Comment by chibill** [comment]
Okay. I am going to work on writing a xml to profile converter. (That uses only built in libs) So you can just pass in the xml from Windows.

**Comment by awkman** [comment]
I merge your PR into pywifi, please check the example in README to confirm the profile usage

**Comment by chibill** [comment]
Looks good. I Wil ltake a closer look at it later today.

**Pull request closed without merging**
